/** Lightweight emoji-to-keyword mapping for search. Only covers emojis used in the picker. */
const EMOJI_NAMES: Record<string, string[]> = {
  // Smileys
  '😀': ['grin', 'happy', 'smile'],
  '😃': ['smile', 'happy', 'grin'],
  '😄': ['smile', 'happy', 'grin'],
  '😁': ['grin', 'beam', 'smile'],
  '😆': ['laugh', 'grin', 'squint'],
  '😅': ['sweat', 'smile', 'nervous'],
  '🤣': ['rofl', 'laugh', 'rolling'],
  '😂': ['joy', 'laugh', 'cry', 'tears'],
  '🙂': ['smile', 'slight'],
  '😊': ['blush', 'smile', 'happy'],
  '😇': ['angel', 'halo', 'innocent'],
  '🥰': ['love', 'hearts', 'adore'],
  '😍': ['heart', 'eyes', 'love'],
  '🤩': ['star', 'struck', 'excited'],
  '😘': ['kiss', 'blow', 'love'],
  '😗': ['kiss', 'whistle'],
  '😚': ['kiss', 'blush'],
  '😙': ['kiss', 'smile'],
  '🥲': ['smile', 'tear', 'sad'],
  '😋': ['yum', 'delicious', 'tongue'],
  '😛': ['tongue', 'playful'],
  '😜': ['wink', 'tongue', 'playful'],
  '🤪': ['zany', 'crazy', 'wild'],
  '😝': ['tongue', 'squint'],
  '🤗': ['hug', 'hands', 'warm'],
  '🤭': ['giggle', 'oops', 'hand'],
  '🫢': ['gasp', 'surprise', 'hand'],
  '🫣': ['peek', 'shy', 'cover'],
  '🤫': ['shush', 'quiet', 'secret'],
  '🤔': ['think', 'hmm', 'wonder'],

  // Animals
  '🐶': ['dog', 'puppy', 'pet'],
  '🐱': ['cat', 'kitten', 'pet'],
  '🐭': ['mouse', 'rodent'],
  '🐹': ['hamster', 'pet'],
  '🐰': ['rabbit', 'bunny'],
  '🦊': ['fox', 'animal'],
  '🐻': ['bear', 'animal'],
  '🐼': ['panda', 'bear'],
  '🐨': ['koala', 'animal'],
  '🐯': ['tiger', 'cat'],
  '🦁': ['lion', 'cat', 'king'],
  '🐮': ['cow', 'animal'],
  '🐷': ['pig', 'animal'],
  '🐸': ['frog', 'toad'],
  '🐵': ['monkey', 'ape'],
  '🙈': ['monkey', 'see', 'no', 'evil'],
  '🙉': ['monkey', 'hear', 'no', 'evil'],
  '🙊': ['monkey', 'speak', 'no', 'evil'],
  '🐔': ['chicken', 'hen', 'bird'],
  '🐧': ['penguin', 'bird'],
  '🐦': ['bird', 'animal'],
  '🐤': ['chick', 'bird', 'baby'],
  '🦆': ['duck', 'bird'],
  '🦅': ['eagle', 'bird'],
  '🦉': ['owl', 'bird', 'wise'],
  '🦇': ['bat', 'animal'],
  '🐺': ['wolf', 'animal'],
  '🐗': ['boar', 'pig', 'wild'],
  '🦄': ['unicorn', 'horse', 'magic'],
  '🐝': ['bee', 'honey', 'insect'],
  '🐕': ['dog', 'pet'],
  '🐈': ['cat', 'pet'],
  '🐙': ['octopus', 'sea'],
  '🦋': ['butterfly', 'insect'],
  '🐳': ['whale', 'sea', 'ocean'],

  // Food & Drink
  '🍎': ['apple', 'red', 'fruit'],
  '🍐': ['pear', 'fruit'],
  '🍊': ['orange', 'tangerine', 'fruit'],
  '🍋': ['lemon', 'citrus', 'fruit'],
  '🍌': ['banana', 'fruit'],
  '🍉': ['watermelon', 'fruit'],
  '🍇': ['grapes', 'fruit'],
  '🍓': ['strawberry', 'fruit', 'berry'],
  '🫐': ['blueberry', 'berry', 'fruit'],
  '🍈': ['melon', 'fruit'],
  '🍒': ['cherry', 'fruit'],
  '🍑': ['peach', 'fruit'],
  '🥭': ['mango', 'fruit'],
  '🍍': ['pineapple', 'fruit'],
  '🥝': ['kiwi', 'fruit'],
  '🍅': ['tomato', 'vegetable'],
  '🥑': ['avocado', 'fruit'],
  '🍆': ['eggplant', 'aubergine'],
  '🌽': ['corn', 'maize', 'vegetable'],
  '🥕': ['carrot', 'vegetable'],
  '🧄': ['garlic', 'vegetable'],
  '🧅': ['onion', 'vegetable'],
  '🥔': ['potato', 'vegetable'],
  '🍠': ['sweet', 'potato', 'yam'],
  '🌶️': ['pepper', 'hot', 'chili', 'spicy'],
  '🥒': ['cucumber', 'vegetable'],
  '🥬': ['lettuce', 'leafy', 'vegetable'],
  '🥦': ['broccoli', 'vegetable'],
  '🧈': ['butter', 'dairy'],
  '🍕': ['pizza', 'food'],
  '☕': ['coffee', 'drink', 'hot', 'cup'],
  '🍔': ['burger', 'hamburger', 'food'],
  '🎂': ['cake', 'birthday', 'dessert'],
  '🍿': ['popcorn', 'snack', 'movie'],
  '🥤': ['cup', 'straw', 'drink', 'soda'],
  '🍩': ['donut', 'doughnut', 'dessert'],
  '🧁': ['cupcake', 'dessert'],
  '🌮': ['taco', 'food', 'mexican'],

  // Nature
  '🌸': ['cherry', 'blossom', 'flower', 'spring'],
  '🌺': ['hibiscus', 'flower'],
  '🌻': ['sunflower', 'flower'],
  '🌹': ['rose', 'flower', 'red'],
  '🌷': ['tulip', 'flower'],
  '🌼': ['daisy', 'flower', 'blossom'],
  '🌵': ['cactus', 'desert', 'plant'],
  '🌲': ['tree', 'evergreen', 'pine', 'forest'],
  '🌳': ['tree', 'deciduous', 'oak'],
  '🌴': ['palm', 'tree', 'tropical'],
  '🍀': ['clover', 'luck', 'shamrock', 'four', 'leaf'],
  '🍁': ['maple', 'leaf', 'fall', 'autumn'],
  '🍂': ['fallen', 'leaf', 'autumn'],
  '🍃': ['leaf', 'wind', 'nature'],
  '🌾': ['rice', 'wheat', 'grain', 'plant'],
  '🌱': ['seedling', 'sprout', 'plant', 'grow'],
  '🪴': ['potted', 'plant', 'houseplant'],
  '🎍': ['bamboo', 'plant'],
  '🪸': ['coral', 'reef', 'ocean'],
  '🍄': ['mushroom', 'fungus'],
  '🪨': ['rock', 'stone', 'boulder'],
  '🌍': ['earth', 'globe', 'world', 'africa', 'europe'],
  '🌎': ['earth', 'globe', 'world', 'americas'],
  '🌏': ['earth', 'globe', 'world', 'asia'],
  '🌕': ['moon', 'full'],
  '🌙': ['moon', 'crescent', 'night'],
  '⭐': ['star', 'yellow'],
  '🌟': ['star', 'glow', 'sparkle'],
  '💫': ['dizzy', 'star', 'sparkle'],
  '✨': ['sparkles', 'magic', 'shine'],
  '🌊': ['wave', 'ocean', 'water', 'sea'],
  '🔥': ['fire', 'flame', 'hot', 'lit'],
  '🌿': ['herb', 'leaf', 'plant', 'green'],
  '🌈': ['rainbow', 'color'],
  '☀️': ['sun', 'sunny', 'bright', 'weather'],

  // Objects
  '📦': ['package', 'box', 'delivery'],
  '💻': ['laptop', 'computer', 'code'],
  '🖥️': ['desktop', 'computer', 'monitor'],
  '⌨️': ['keyboard', 'type', 'input'],
  '🖱️': ['mouse', 'computer', 'click'],
  '⚙️': ['gear', 'settings', 'cog'],
  '🔧': ['wrench', 'tool', 'fix'],
  '🛠️': ['tools', 'hammer', 'wrench'],
  '🔌': ['plug', 'electric', 'power'],
  '📡': ['satellite', 'antenna', 'signal'],
  '🔬': ['microscope', 'science', 'lab'],
  '🧪': ['test', 'tube', 'science', 'lab'],
  '🔭': ['telescope', 'space', 'astronomy'],
  '📱': ['phone', 'mobile', 'cell'],
  '💾': ['floppy', 'disk', 'save'],
  '💿': ['cd', 'disk', 'disc'],
  '📀': ['dvd', 'disk', 'disc'],
  '🎥': ['camera', 'movie', 'film'],
  '📷': ['camera', 'photo'],
  '📸': ['camera', 'flash', 'photo'],
  '🔑': ['key', 'lock', 'password'],
  '🔒': ['lock', 'secure', 'closed'],
  '🗝️': ['key', 'old', 'skeleton'],
  '🧰': ['toolbox', 'tools'],
  '📐': ['ruler', 'triangle', 'math'],
  '📎': ['paperclip', 'clip', 'attach'],
  '🖊️': ['pen', 'write'],
  '✏️': ['pencil', 'write', 'edit'],
  '🔗': ['link', 'chain', 'url'],
  '📌': ['pin', 'pushpin', 'location'],
  '📁': ['folder', 'file', 'directory'],
  '📂': ['folder', 'open', 'file'],
  '📋': ['clipboard', 'paste'],
  '📝': ['memo', 'note', 'write'],
  '📄': ['page', 'document', 'file'],
  '📑': ['tabs', 'bookmark', 'document'],
  '🗂️': ['dividers', 'tabs', 'file'],
  '💼': ['briefcase', 'work', 'business'],
  '🎒': ['backpack', 'bag', 'school'],

  // Tech & Science
  '🔩': ['nut', 'bolt', 'screw'],
  '🔨': ['hammer', 'tool', 'build'],
  '📊': ['chart', 'bar', 'graph', 'data'],
  '📈': ['chart', 'up', 'growth', 'graph'],
  '📉': ['chart', 'down', 'decline', 'graph'],
  '🧮': ['abacus', 'math', 'count'],
  '🧬': ['dna', 'genetics', 'science'],
  '🔎': ['search', 'magnifying', 'glass', 'zoom'],
  '🔍': ['search', 'magnifying', 'glass', 'zoom'],
  '💡': ['bulb', 'light', 'idea'],
  '⚡': ['lightning', 'bolt', 'electric', 'power', 'zap'],
  '📧': ['email', 'mail', 'envelope'],
  '✉️': ['envelope', 'mail', 'letter'],
  '📮': ['postbox', 'mail'],
  '📯': ['horn', 'postal'],
  '💬': ['speech', 'bubble', 'chat', 'message'],
  '💭': ['thought', 'bubble', 'think'],
  '📢': ['loudspeaker', 'announce'],
  '📣': ['megaphone', 'announce', 'cheer'],
  '🛰️': ['satellite', 'space', 'orbit'],

  // Transport
  '🚀': ['rocket', 'launch', 'space', 'ship'],
  '✈️': ['airplane', 'plane', 'travel', 'fly'],
  '🚁': ['helicopter', 'fly'],
  '🚂': ['train', 'locomotive', 'steam'],
  '🚗': ['car', 'automobile', 'drive'],
  '🛸': ['ufo', 'alien', 'flying', 'saucer'],
  '⛵': ['sailboat', 'boat', 'sail'],
  '🏎️': ['race', 'car', 'formula'],
  '🚧': ['construction', 'barrier', 'warning'],

  // Symbols
  '❤️': ['heart', 'red', 'love'],
  '🧡': ['heart', 'orange'],
  '💛': ['heart', 'yellow'],
  '💚': ['heart', 'green'],
  '💙': ['heart', 'blue'],
  '💜': ['heart', 'purple'],
  '🖤': ['heart', 'black'],
  '🤍': ['heart', 'white'],
  '🤎': ['heart', 'brown'],
  '💔': ['broken', 'heart'],
  '❤️‍🔥': ['heart', 'fire', 'passion'],
  '💯': ['hundred', 'perfect', 'score'],
  '✅': ['check', 'done', 'yes', 'green'],
  '❌': ['cross', 'no', 'wrong', 'red'],
  '⭕': ['circle', 'ring', 'red'],
  '🔴': ['red', 'circle'],
  '🟠': ['orange', 'circle'],
  '🟡': ['yellow', 'circle'],
  '🟢': ['green', 'circle'],
  '🔵': ['blue', 'circle'],
  '🟣': ['purple', 'circle'],
  '⚫': ['black', 'circle'],
  '⬜': ['white', 'square'],
  '🔶': ['orange', 'diamond'],
  '🔷': ['blue', 'diamond'],
  '🔺': ['red', 'triangle', 'up'],
  '🔻': ['red', 'triangle', 'down'],
  '💠': ['diamond', 'blue', 'dot'],
  '🏁': ['flag', 'checkered', 'finish', 'race'],
  '💎': ['gem', 'diamond', 'jewel'],
  '🏆': ['trophy', 'award', 'winner', 'cup'],
  '🎖️': ['medal', 'military', 'award'],
  '🏅': ['medal', 'sports', 'award', 'gold'],
  '👑': ['crown', 'king', 'queen', 'royal'],
  '💰': ['money', 'bag', 'dollar', 'rich'],
  '💳': ['credit', 'card', 'payment'],

  // Activities
  '⚽': ['soccer', 'football', 'ball', 'sport'],
  '🏀': ['basketball', 'ball', 'sport'],
  '🏈': ['football', 'american', 'sport'],
  '⚾': ['baseball', 'ball', 'sport'],
  '🎾': ['tennis', 'ball', 'sport'],
  '🏐': ['volleyball', 'sport'],
  '🏉': ['rugby', 'sport'],
  '🎱': ['billiards', 'pool', 'eight', 'ball'],
  '🏓': ['ping', 'pong', 'table', 'tennis'],
  '🏸': ['badminton', 'sport'],
  '🥅': ['goal', 'net', 'sport'],
  '🏒': ['hockey', 'ice', 'sport'],
  '🏑': ['hockey', 'field', 'sport'],
  '🥊': ['boxing', 'glove', 'sport'],
  '🎮': ['game', 'controller', 'video', 'play'],
  '🎯': ['target', 'dart', 'bullseye'],
  '🎳': ['bowling', 'sport'],
  '🎸': ['guitar', 'music', 'rock'],
  '🎹': ['piano', 'keyboard', 'music'],
  '🎺': ['trumpet', 'music', 'brass'],
  '🎻': ['violin', 'music', 'string'],
  '🪘': ['drum', 'music', 'percussion'],
  '🎨': ['art', 'palette', 'paint', 'color'],
  '🎬': ['clapper', 'movie', 'film', 'action'],
  '🎤': ['microphone', 'sing', 'karaoke'],
  '🎧': ['headphones', 'music', 'audio'],
  '📚': ['books', 'read', 'study', 'library'],
  '🎭': ['theater', 'drama', 'masks', 'performing'],
  '🃏': ['joker', 'card', 'wild'],
  '♟️': ['chess', 'pawn', 'game', 'strategy'],
  '🏋️': ['weightlifting', 'gym', 'exercise'],
  '🧗': ['climbing', 'rock', 'sport'],
  '🏄': ['surfing', 'wave', 'sport'],
  '🎲': ['dice', 'game', 'random', 'chance'],
  '🎵': ['music', 'note', 'song'],

  // Health
  '🏥': ['hospital', 'health', 'medical'],
  '💊': ['pill', 'medicine', 'drug'],
  '🩺': ['stethoscope', 'doctor', 'medical'],
  '🩹': ['bandage', 'adhesive', 'heal'],
  '❤️‍🩹': ['mending', 'heart', 'heal'],
  '🧠': ['brain', 'mind', 'think', 'smart'],
  '👁️': ['eye', 'see', 'look', 'vision'],
  '💉': ['syringe', 'needle', 'vaccine'],
  '🦷': ['tooth', 'dental'],
  '🫀': ['heart', 'organ', 'anatomical'],
}

/** Returns true if the emoji matches the search query (by character or name). */
export function emojiMatchesSearch(emoji: string, query: string): boolean {
  if (emoji.includes(query)) return true
  const lowerQuery = query.toLowerCase()
  const names = EMOJI_NAMES[emoji]
  return names ? names.some(name => name.includes(lowerQuery)) : false
}
