import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { useTicketAction } from '@/hooks/useTickets'
import { PhaseLogPanel } from './PhaseLogPanel'
import type { Ticket } from '@/hooks/useTickets'

interface InterviewQAViewProps {
  ticket: Ticket
}

export function InterviewQAView({ ticket }: InterviewQAViewProps) {
  const { mutate: performAction, isPending } = useTicketAction()

  return (
    <div className="h-full flex flex-col overflow-hidden">
      <div className="p-4 space-y-3 shrink-0">
        <Card>
          <CardHeader className="py-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm">Interview Q&A</CardTitle>
              <Badge variant="outline" className="text-xs">Q 0/50</Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-3 pb-3">
            <div className="rounded-lg border border-border p-3 bg-accent/30">
              <div className="text-[10px] text-muted-foreground mb-1 uppercase tracking-wider">Current Question</div>
              <p className="text-xs font-medium">
                Interview questions will be generated by the council and presented here.
              </p>
            </div>

            <textarea
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-xs min-h-[60px]"
              placeholder="Type your answer here…"
            />

            <div className="flex gap-2 justify-end">
              <Button variant="outline" size="sm" disabled className="h-7 text-xs">Skip</Button>
              <Button size="sm" disabled className="h-7 text-xs">Submit</Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => performAction({ id: ticket.id, action: 'cancel' })}
                disabled={isPending}
                className="h-7 text-xs text-destructive"
              >
                Cancel
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="flex-1 min-h-0 px-4 pb-4 flex flex-col">
        <PhaseLogPanel phase="WAITING_INTERVIEW_ANSWERS" />
      </div>
    </div>
  )
}
